version: '3'
services:
  backend:
    build: .  # Path to your backend project directory
    ports:
      - "8080:8080"
    depends_on:
      - db

  front:
    build: ./src/main/webapp/reactjs  # Path to the directory where your frontend Dockerfile is located
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: monsterlegends@2002
      MYSQL_DATABASE: incidents
      MYSQL_USER: incidents
      MYSQL_PASSWORD: abcd@1234
    ports:
      - "3307:3307"
